# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    max: 25
    item_par_page: 3

services:
    service_extractResume:
        class: AppBundle\Tools\Libstrlib
        arguments: ["@session", "[...]", "%max%"]
        tags:
            - {name: twig.extension}

    service_maintenance:
        class: AppBundle\Listener\MaintenanceListener
        arguments: [false, "@templating"]
        tags:
            - {name: kernel.event_listener, event: kernel.response, methode: onKernelResponse}
            
